### PR TITLE
Config only one auth system by deployment (dev & prod)

### PR DESCRIPTION
**Pull request by tangrammer**
ready

### CODE REVIEW

**Comment by tangrammer** [comment]
@dlebrero @kardan 
please don't merge until we have the "thing" ready on lumen-backend!!

**Comment by dlebrero** [comment]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by tangrammer** [comment]
@dlebrero @kardan 
IMO, it could be merged without breaking anything on lumen side

Once that we had the next lumen version deployed, I'll set up another PR here (akvo-platform) to remove the vars not used anymore (nor live, dark, test or prod envs)

**Comment by dlebrero** [comment]
Remember that changes must be applied manually!

**Pull request merged**
