### PR TITLE
Paginate over the GitHub repo list end-point, if required

### PR DESCRIPTION
**Pull request by punchagan**
This PR also has a commit to get the script to work in the DATA_DIR (`/tmp/akvo/github-pull-reminders`) to avoid duplicating the path to the DATA_DIR.

### CODE REVIEW

**Comment by punchagan** [comment]
I think we don't really need to paginate if we are fetching repositories sorted by their last updated time, and fetching 100 repositories. I can get rid of the commit that adds pagination, if it seems like extra complexity in the code with not much gain.

**Review by iperdomo — CHANGES_REQUESTED** [review]
* I think we're going too far on the pagination part. We don't have hundreds of repos.
* We need to process only the repos that are **not** archived

**Comment by iperdomo** [comment]
It seems that when listing the repos we can't filter out the `archived:true` repos, so we need to filter them *after* we got the full list

**Comment by punchagan** [comment]
> * I think we're going too far on the pagination part. We don't have hundreds of repos.

Fair enough. I've removed that commit.

> * We need to process only the repos that are **not** archived

Nice catch, I've added a commit to do this.

**Review by iperdomo — APPROVED** [review]

**Pull request merged**
